In [1]:
# o	Import the NumPy library
import numpy as np

In [2]:
# o	Create a 1-dimensional NumPy array with values ranging from 0 to 9.
oned_arr = np.arange(10)

In [3]:
oned_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# o	Create a 3x3 NumPy array of all True’s (boolean).
bool_arr = np.full((3,3,3), True)

In [5]:
bool_arr

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [6]:
# o	Extract all odd numbers from the array created in the first step.
odd_list = oned_arr[oned_arr % 2 == 1]

In [7]:
odd_list 

array([1, 3, 5, 7, 9])

In [8]:
# o	Replace all odd numbers in the array with -1 without changing the original array.
replaced_array = np.where(oned_arr % 2 == 1, -1, oned_arr)

In [9]:
replaced_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
# Create a 2-dimensional array of shape (5,5) with sequential numbers from 1 to 25.
twod_arr = np.arange(1,26).reshape(5,5)

In [19]:
twod_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
# Extract the second row and the third column from the array.
extracted_arr = twod_arr[2, 3]

In [23]:
extracted_arr

np.int64(14)

In [44]:
# Extract a subarray of 3x3 from the top-right corner of the array.
topright_arr = twod_arr[:3, -3:]

In [45]:
topright_arr

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [57]:
#o	Create two arrays of shape (3,3): one filled with 3's and another with 5's.
arr1 = np.full((3,3), 3)
arr2 = np.full((3,3), 5)


In [59]:
arr1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [60]:
arr2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [62]:
# o	Stack these two arrays vertically and horizontally (use vstack and hstack).
vertical = np.vstack((arr1,arr2))
horizontal = np.hstack((arr1,arr2))

In [63]:
vertical

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [64]:
horizontal

array([[3, 3, 3, 5, 5, 5],
       [3, 3, 3, 5, 5, 5],
       [3, 3, 3, 5, 5, 5]])

In [65]:
#o	Split the stacked array horizontally at the second index.
split_arr = np.hsplit(horizontal, [2])

In [66]:
split_arr

[array([[3, 3],
        [3, 3],
        [3, 3]]),
 array([[3, 5, 5, 5],
        [3, 5, 5, 5],
        [3, 5, 5, 5]])]

In [67]:
# o	Create a 1-dimensional array of 12 random numbers.
darr = np.random.rand(12)

In [68]:
darr

array([0.97134909, 0.05707128, 0.86672253, 0.10758111, 0.7870444 ,
       0.04968632, 0.5458238 , 0.99821069, 0.71971566, 0.37085505,
       0.43475862, 0.2481595 ])

In [69]:
#o	Calculate the mean, median, and standard deviation of the array.
mean = np.mean(darr)
median = np.median(darr)
stand_dev = np.std(darr)

In [70]:
mean

np.float64(0.5130815054584645)

In [71]:
median

np.float64(0.4902912115516499)

In [72]:
stand_dev

np.float64(0.3382435497414694)

In [73]:
#o	Normalize the array (subtract the mean and divide by the standard deviation).
min = np.min(darr)
max = np.max(darr)
normlized = (darr - min) / (max - min)

In [74]:
min

np.float64(0.049686321000369515)

In [75]:
max

np.float64(0.9982106936581174)

In [76]:
normlized

array([0.97168064, 0.00778573, 0.86137609, 0.06103669, 0.77737389,
       0.        , 0.52306245, 1.        , 0.70639127, 0.33859829,
       0.40596986, 0.20924416])